<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Laporan_pemesanan_model extends CI_Model
{

    public $table = 'laporan_pemesanan';
    public $id = '';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        // $this->db->like('', $q);
        $this->db->or_like('tanggal', $q);
        $this->db->or_like('id_jadwal', $q);
        $this->db->or_like('tiket_terjual', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        // $this->db->like('', $q);
        $this->db->or_like('tanggal', $q);
        $this->db->or_like('id_jadwal', $q);
        $this->db->or_like('tiket_terjual', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }
    function total_rows_tujuan($q = NULL, $id_jadwal)
    {
        // $this->db->like('', $q);
        $this->db->where('id_jadwal', $id_jadwal);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data_tujuan($limit, $start = 0, $q = NULL, $id_jadwal)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->where('id_jadwal', $id_jadwal);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }
    function total_rows_tanggal($q = NULL, $dari, $sampai)
    {
        // $this->db->like('', $q);
        $this->db->where('tanggal >=', $dari);
        $this->db->where('tanggal <=', $sampai);

        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data_tanggal($limit, $start = 0, $q = NULL, $dari, $sampai)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->where('tanggal >=', $dari);
        $this->db->where('tanggal <=', $sampai);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    // delete bulkdata
    function deletebulk()
    {
        $data = $this->input->post('msg_', TRUE);
        $arr_id = explode(",", $data);
        $this->db->where_in($this->id, $arr_id);
        return $this->db->delete($this->table);
    }
}

/* End of file Laporan_pemesanan_model.php */
/* Location: ./application/models/Laporan_pemesanan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-08-15 16:04:49 */
/* http://harviacode.com */